
#GET THE DEPARTMENT NAME WHICH HAS MORE NUMBER OF EMPLOYEES WHOSE LAST NAME START WITH 'A'

SELECT DEPARTMENTID,DEPARTMENTNAME FROM DEPARTMENT WHERE DEPARTMENTID IN (
SELECT DEPARTMENTID FROM EMPLOYEE WHERE UPPER(LASTNAME) LIKE 'A%' GROUP BY DEPARTMENTID HAVING COUNT(DEPARTMENTID)=(SELECT MAX(E_MAX) FROM 
(SELECT DEPARTMENTID,COUNT(DEPARTMENTID) AS E_MAX FROM EMPLOYEE WHERE UPPER(LASTNAME) LIKE 'A%' GROUP BY DEPARTMENTID) A))